---
- hosts: cisco
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "user_to_be_changed"
      prompt: "what user do you want to change?"
    - name: "new_password"
      prompt: "what is the password you want?"
  tasks:
    - nxos_config:
        provider: "{{ login_info }}"
        lines: "username {{user_to_be_changed}} password {{new_password}}"
        save_when: always
