---
- hosts: cisco
  connection: local
  vars_prompt:
    - name: "user_to_be_changed"
      prompt: "what user do you want to change?"
    - name: "new_password"
      prompt: "what is the password you want?"
  tasks:
    - nxos_command:
        provider: "{{ login_info }}"
        commands: "username {{user_to_be_changed}} password {{new_password}}"
